#!/bin/bash
echo "What is the username of the user you want to delete ?"
read username
`top U test -b -n 1 | grep "test" | sed 's/  */ /g' | cut -d ' ' -f2 > ${username}_pid_list`
pid_count=`wc -l ${username}_pid_list | cut -d ' ' -f1`
for i in `seq 1 $pid_count`
do
	pid=`cat ${username}_pid_list | sed -n ${i}p`
	echo $pid
	`sudo kill $pid`
done
`sudo userdel -r $username`
rm ${username}_pid_list
